FROM golang:1.18 as builder

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ADD . /gonymizer
WORKDIR /gonymizer/cmd

RUN go build -o ../bin/gonymizer .

# Package Stage
FROM debian:bookworm-slim
COPY --from=builder /gonymizer/bin/gonymizer /