FROM golang:1.18

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ADD . /gonymizer
WORKDIR /gonymizer/cmd

RUN go build -o ../bin/gonymizer .

WORKDIR /gonymizer/bin